services:
- type: web
  name: rabbitmq
  env: docker
  healthCheckPath: /
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    value: rH2fGmRGjEOFWdOF9PYZWAWp92TTs0Z+sQtCJinH
  - key: RABBITMQ_DEFAULT_USER
    value: snowcore
  - key: RABBITMQ_DEFAULT_PASS
    value: snowcore@2026#
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq
    sizeGB: 10
